version: '3'
services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'elle'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'elle'
    webapp:
        build: .
        depends_on:
            - db
        ports:
            - 5001:8081
        environment:
            - DB_HOST=db
            - DB_USER='root'
            - DB_PASSWORD='elle'
        links:
            - db
        stdin_open: true
        tty: true